### ISSUE TITLE
provide a letsencrypt

### ISSUE THREAD

**Issue by pigeonflight** [plone/ansible.plone_server#122]
It should be possible to deploy plone with letsencrypt.
Here's a post on ansible, nginx and letsencrypt https://medium.com/@flawless_retard/generating-lets-encrypt-certificates-for-nginx-using-ansible-9fd27b90993a

It looks like we would just need to add a "letsencrypt" role.

**Comment by gp54321** [comment]
I don't understand why you are recreating an issue here, as I understand it, plone-server is for Plone specific configuration, buildout and the like, while there is already an existing [one](https://github.com/plone/ansible-playbook/issues/61)  on ansible-plone that seems a more appropriate place for this kind of system question.

**Comment by pigeonflight** [comment]
Good to know. https://github.com/plone/ansible-playbook/issues/61
I'll close this one so that it is only reported in one location.

**Comment by pigeonflight** [comment]
@gp54321 apparently I had +1'd the https://github.com/plone/ansible-playbook/issues/61 bug and totally forgot.
