### ISSUE TITLE
buildout.sanitycheck fails, "Run buildout" is not run as plone_buildout

### ISSUE THREAD

**Issue by htgoebel** [plone/ansible.plone_server#13]
When running this role on a Vagrant machine I get the error shown below. It looks like ansible does not honour the `sudo_user:` entry.

Any idea how to solve this – except of changing the commands into `sudo ... ?, of course :-)

- ansible 1.8.1
- ansible.plone_server 1.0b6 (from galaxy)

Inventory:
```
test ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant
```

Shortend error message:
```
failed: [test] => {"changed": true, "cmd": ["bin/buildout"], "delta": "...", "end": "...", "rc": 1, "start": "...", "warnings": []}
stderr: While:
  Installing.
  Loading extensions.
Error: User attempt to give system ownership to Internet
stdout: buildout.sanitycheck: 
***********************************************************
Buildout should not be run while superuser. Doing so allows
untrusted code to be run as root.
Instead, you probably wish to do something like:
    sudu -u plone_buildout bin/buildout
```

**Comment by htgoebel** [comment]
Edit: I have version 1.0b6 from galaxy. Corrected in first comment.

**Comment by smcmahon** [comment]
Documentation updated to clarify the expectation that this role is meant to be run as part of a playbook with sudo set to "yes."

**Comment by htgoebel** [comment]
@smcmahon I've been running the playbook with "sudo set to" when the issue occured. See the inventory line I posted.

**Comment by htgoebel** [comment]
@smcmahon: I have set `ansible_sudo: true` in the hosts_vars defined in the ansible inventory. Please see 
https://github.com/plone/ansible.plone_server/pull/16#issuecomment-73474964 for a more detailed analysis. If you apply #16 you can remove the restriction you just documented.
