### ISSUE TITLE
Re-running role does not re-run "Run buildout"

### ISSUE THREAD

**Issue by htgoebel** [plone/ansible.plone_server#14]
When "Run buildout" fails, (see issue #13) re-running the role does not re-run "Run buildout". Instead this will be skipped. The reason is:
```
- name: Run buildout
when: plone_autorun_buildout and instance_status.changed
```
But `instance_status.changed` is only true when the buildout.cfg has changed. So we'd need some other or additional condition.

**Comment by djowett** [comment]
@smcmahon I'm seeing this issue too, or more specifically that re-running ansible doesn't consistently re-run a failed buildout.
Can we pull this fix by @zylinx into the main repo?

**Comment by djowett** [comment]
Ah, sorry, I see this *IS* already merged.  My ansible didn't seem to react to a `git pull` in quite the way I thought it might....  I think I need to run 

     ansible-galaxy -p roles -r requirements.txt install

**Comment by smcmahon** [comment]
Fixed when zylinx changes were merged.
