### ISSUE TITLE
Error when using --start-at="Run buildout"

### ISSUE THREAD

**Issue by htgoebel** [plone/ansible.plone_server#15]
Then running the role with `--start-at="Run buildout"`, one gets the error
```
fatal: [test] => error while evaluating conditional: plone_autorun_buildout and instance_status.changed
```
The reason is that "Copy buildout template" is not run and thus `instance_status` is undefined.

As a work-around, the condition could be changed into
```plone_autorun_buildout and instance_status is defined and instance_status.changed
```
Solving this issue would require a different condition, see issue #14 .

**Comment by smcmahon** [comment]
Since we're doing various checks that are important to evaluating the need to run buildout well before that step, I don't think we'll ever be able to support jumping over all prior steps.
