### ISSUE TITLE
restart_clients.sh should go into `{{ plone_instance_home }}/bin`

### ISSUE THREAD

**Issue by htgoebel** [plone/ansible.plone_server#24]
Putting it into `{{ plone_instance_home }}/scripts` hides it from the admin. Is there any reason for putting it into `scripts`?

**Comment by fulv** [comment]
+1

**Comment by smcmahon** [comment]
The script was intended to be a bit hard to find, so that it would force an admin to read and think about it before using it.

The more I think about it, the more I'm sure it doesn't belong in the role at all.
