### ISSUE TITLE
Sleep times in restart_clients

### ISSUE THREAD

**Issue by fulv** [plone/ansible.plone_server#28]
https://github.com/plone/ansible.plone_server/blob/master/templates/restart_clients.sh.j2#L15

Why is there a 40 second delay after stopping a client, and only a 10 second delay after starting?
It seems to me like it should be the other way around, as it always takes a very short time to stop, but longer to start.
On my sites, I inverted those two sleeps, anyway.

And I also add 

```
/usr/sbin/service varnish restart
/usr/sbin/service nxinx restart
```

for good measure.

**Comment by smcmahon** [comment]
There's a trick that interacts with haproxy settings from the plone ansible playbook. I don't know if it's tuned up perfectly, but it's worked in my tests. 

The long delay after stopping is meant to ensure that haproxy marks the client as down.

On the start side, we've got http fast listen turned on in the client, so it should accept connections very rapidly. But haproxy should not mark it up until it passes three health checks. The goal is to sneak in our homepage fetch well before haproxy will have marked the client up. That should warm our cache up a bit before it's added to the haproxy up list.

At a minimum, this needs better documentation. It's a complex interaction with a setting in another playbook and thus won't work if the load balancer is differently configured.

Also, note that fiddling varnish and nginx afterwards is basically making the same assumption: that the delivery stack includes varnish and nginx.

I think this means that this script really belongs in the full-stack playbook, not the plone server role.

Thoughts?

**Comment by smcmahon** [comment]
More thoughts. The right way to solve the problem is by directly controlling the load balancer. Of course, that's more reason to move this script out of this role.

**Comment by fulv** [comment]
Thanks for the explanation, and I understand that it would make sense to take this out of the role.

Not to beat a dead horse, but just for my education:  if you only have two clients, and only wait 10 seconds after starting the first one before stopping the second client, aren't you guaranteeing a 50x error for a user who loads a page in that minute or so?  At least, that's what I've seen.

**Comment by smcmahon** [comment]
If fast listen is on, the first thing zope does is start listening. This is not necessarily a good idea, unless you're making sure that the client is still marked down.

In any case, I think this is improved in a new version that's in the full-stack playbook.
