### ISSUE TITLE
Duplicate cron jobs

### ISSUE THREAD

**Issue by djowett** [plone/ansible.plone_server#39]
It seems that updating to 1.1.1 including 5cce05da has left me with duplicate cron jobs.  I can just remove them manually (not the Ansible way), but thought it worth noting.

    root@mysite:/etc# crontab -u plone_daemon -l
    #Ansible: Plone packing
    30 1 * * 7 cd /usr/local/plone-4.3/zeoserver && bin/zeopack
    #Ansible: Plone backup
    30 2 * * * cd /usr/local/plone-4.3/zeoserver && bin/backup
    #Ansible: zeoserver Plone packing
    30 1 * * 7 cd /usr/local/plone-4.3/zeoserver && bin/zeopack
    #Ansible: zeoserver Plone backup
    30 2 * * * cd /usr/local/plone-4.3/zeoserver && bin/backup

**Comment by djowett** [comment]
Ah...
# Ensure an old job is no longer present. Removes any job that is prefixed
# by "#Ansible: an old job" from the crontab
- cron: name="an old job" state=absent

**Comment by smcmahon** [comment]
I should have gotten to this earlier. I think this is good advice for the future, but not work fixing for the past.
