### ISSUE TITLE
install older Plone versions

### ISSUE THREAD

**Issue by fulv** [plone/ansible.plone_server#4]
I'm trying to use this with ansible-playbook to install an older Plone version, specifically 4.2.5.  
No matter what I use in `plone_major_version` and `plone_version`, the versions.cfg file that is referred to in buildout.cfg's extends line is still the one for the latest version.

**Comment by smcmahon** [comment]
Indeed. This needs fixing.

**Comment by smcmahon** [comment]
Fixed in 1.0b7

**Comment by fulv** [comment]
Whoa, cool!
