### ISSUE TITLE
Error creating base directory, it creates /usr/local/plone- (without version)

### ISSUE THREAD

**Issue by oggers** [plone/ansible.plone_server#48]
At some point it creates the directory defined by {{ instance_config.plone_target_path }}.

This variable is calculated from:
```
plone_target_path: "{{ plone_config.plone_target_path|default('/usr/local/plone-' + work_major_version) }}"
```
And in case plone_config.plone_target_path is not defined, it looks at:
```
work_major_version: "{{ work_version|truncate(length=3, end='') }}"
```
And here truncating "4.3.7" results in empty string, you should change the truncate filter to:
```
truncate(length=3, killwords=true, end='')
```

**Comment by smcmahon** [comment]
Fixed in e494768. Thanks!
