### ISSUE TITLE
Enhancement: Plone multi-client single-server setup 

### ISSUE THREAD

**Issue by pe82** [plone/ansible.plone_server#69]
It would be great if we could use ansible to deploy (install and cofigure) a multi-client single-server setup. All machines would be discrete units.

**Comment by smcmahon** [comment]
If, by "multi-client" you mean able to install multiple Plone instances on the same server, this is done. See  https://github.com/plone/ansible-playbook/blob/master/docs/multiserver.rst and https://github.com/plone/ansible-playbook/blob/master/sample-multiserver.yml
