### ISSUE TITLE
Buildout is not automatically rerun when files from plone_buildout_extra_dir are changed

### ISSUE THREAD

**Issue by djowett** [plone/ansible.plone_server#70]
I guess `Run buildout` needs to consider a variable registered in `Copy files from the buildout extra dir`

cc @Gomez 

I'll probably get to this at somepoint, but not immediately.

**Comment by smcmahon** [comment]
Good point!

**Comment by smcmahon** [comment]
Fixed by 1db77c1

**Comment by djowett** [comment]
Thanks! All good from where I'm sitting ([small spelling correction](https://github.com/plone/ansible.plone_server/commit/516481987041b27f8c3da12d70dc515848a593f8) added direct to master - with unintentionally ironic commit msg)
