### ISSUE TITLE
Problem with git shallow clone (clone --depth)

### ISSUE THREAD

**Issue by Gomez** [plone/ansible.plone_server#77]
We deploy our test servers with this role. As we need to change branches on the test server we need a full clone, instead of the depth=1.

Is there a advantage or would drop the depth a option:
https://github.com/plone/ansible.plone_server/blob/master/tasks/main.yml#L147

**Comment by smcmahon** [comment]
I think that was a premature optimization. If you want to fix it, go ahead!
