### ISSUE TITLE
Changing plone_client_max_memory doesn't take effect

### ISSUE THREAD

**Issue by djowett** [plone/ansible.plone_server#79]
In my case I updated 250MB to 300MB, but found that memmon restarted a process running at 260MB.

From a `ps -ef` analysis I can see that supervisord was *not* restarted when I ran Ansible. Reading around this, it seems there are some caveats of running `supervisor update` - it seems it may not restart relevant processes - in my case memmon.  Perhaps we should be sending a SIGHUP to supervisord?

Brain dump of links
http://www.onurguzel.com/supervisord-restarting-and-reloading/  ( a bit old)
http://supervisord.org/running.html
https://github.com/Supervisor/supervisor/issues/720

**Comment by djowett** [comment]
Manually intervening on the host as follows:

  `supervisorctl update`
   => error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 224
  `sudo supervisorctl update`
  => No error, but doesn't restart processes (as seen by  supervisorctl status)
  `sudo supervisorctl reread`
  => No config updates to processes
  `sudo supervisorctl reload`
  => seemed to work and definitely restarted zeoclient, 
       so assume memmon was ALSO restarted with correct settings
 `sudo kill -HUP $(cat /var/run/supervisord.pid)`
  => also seems to work & def restarts zeoclient

However after all this, supervisord still didn't restart, so perhaps my earlier worry about that was misplaced?

    ps -ef | grep super
    root      1288     1  0 May10 ?        00:06:57 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

I'm not sure where to go with this....

**Comment by smcmahon** [comment]
Fixed in https://github.com/plone/ansible.plone_server/pull/89/commits/3c7e8d26a3a698a9a526ccdce0d6d52802e66a2d

**Comment by djowett** [comment]
Thanks @smcmahon - I can confirm it works this end - even if just adding distinct value for `plone_client_max_memory` in playbook_plones.
